### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by Sinasta** [wassimj/topologicsverchok#5]
Hi, thank you very much for your impressive work. You are doing an incredible gift for the opensource community. I am new to topologic and i would love to get some information to how to get started with this addon. If you would qve some spare time i would greatly appreciate if you could upload a small video or sone general instructions ( possibly with examples) on how to use this addon in general. I know that this is WIP but it already seems quiet usable. Thanks again.

**Comment by Sinasta** [comment]
Oh and a small bug report: i get this error upon activation:

Traceback (most recent call last):
  File "/usr/share/blender/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/sinasta/.config/blender/2.93/scripts/addons/topologicsverchok-main/__init__.py", line 24, in <module>
    blenderName = [name for name in os.listdir(home+"/"+conda) if name.startswith('Blender')][0]
FileNotFoundError: [Errno 2] No such file or directory: '/home/sinasta//opt/anaconda3/envs'

I am using blender 2.93  with systems python 3.9 located at: /usr/lib/python3.9/site-packages on manjaro Linux

**Comment by wassimj** [comment]
Oh there is a double forward slash. Will fix


________________________________

**Comment by wassimj** [comment]
Dear @Sinasta, even if you have 2.93 that uses python 3.9, I suggest you create a virtual environment using conda. The init script assumes that you have cppyy and dependencies installed in ~/opt/anaconda3/lib/site-package and the topologic.0.4 egg installed there as well. If you have different locations, then you need to edit the init file and change the location of the sys.path.append. (But perhaps it is working already because it is using the system file locations?)
Will try to record a quick tutorial for Blender soon. But if you need one-on-one, happy to do so, email me.

**Comment by wassimj** [comment]
The repo has been updated to 0.5.0.2 which fixes the double forward slash issue.
