### ISSUE TITLE
No module named 'TopologicSverchok-v'

### ISSUE THREAD

**Issue by slavingia** [wassimj/TopologicSverchok#53]
```
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/3.5/scripts/modules/addon_utils.py", line 333, in enable mod = import (module name)
ModuleNotFoundError: No module named 'TopologicSverchok-v'
```

**Comment by wassimj** [comment]
This is a very strange name (the addition of v). But in general, the TopologicSverchok software is 'on hold' a bit until we port back topologicpy into Blender. This will happen in a few months. Until then, please consider using topologicpy within Jupyter Notebook. It offers the best experience. Otherwise, you can import topologicpy into Blender and use custom python scripts to access it like you access any 3rd party python library (e.g. numpy or scipy etc).

**Comment by slavingia** [comment]
Is there any way to use Homemaker in Blender until then? I was downloading this in order to enable that.

**Comment by wassimj** [comment]
Oh. Then please post this to Bruno’s GitHub. He may have changed the name of topologic.

**Comment by slavingia** [comment]
Sounds good, thanks!
